### ISSUE TITLE
Create recurring expense

### ISSUE THREAD

**Issue by skrapn** [bminusl/ihatetobudget#5]
Create expense record which will repeat itself automatically on a specific day every X week/month/year (e.g. monthly internet bill, monthly mobile phone bill)

### How to create new recurring expense
1. Click 'New Expense'
2. Select 'Recurring' (non-Recurring being the default) to show the additional options
3. Select interval (week, month, year) and allow integer input for X
4. Select 'Category'
5. Select 'Date' (change label in UI to show as Start Date)
6. Input 'Description'
7. Input 'Amount'
8. Click 'Save'

### How to manage existing recurring expenses
1. Under 'SHEETS' block on the homepage (insert 'Edit recurring expenses' link under 'SETTINGS')
2. On page load, to display list of recurring expenses created (similar template used by 'Edit categories')
3. Click on each recurring expense item on the list will show the settings icon on the right (similar to how it is displayed on 'Edit categories' page)
4. Click the settings icon will show the 'Edit' and 'Delete' options ('Edit' redirects user to a page with the editable values, 'Delete' redirects user to confirmation delete page)

(Thank you for the useful software!)

**Comment by bminusl** [comment]
I've thought about it before, but never found the time/will to do it. So far I have been using the "Duplicate" button, but it's not ideal.

I've dug a little deeper into the subject and will probably copy what other popular software do. I like https://docs.firefly-iii.org/firefly-iii/advanced-concepts/recurring/. It is similar to your proposal.

I will implement this when I find the time. 

> (Thank you for the useful software!)

I appreciate that! I'm glad it is useful.

**Comment by virtadpt** [comment]
Please!  This is essential for bill triage.

**Comment by skrapn** [comment]
@bminusl Holy smokes you are fast! Thanks!

On a side note, I've never noticed the duplicate function. That might come in handy someday.
