### ISSUE TITLE
Ampersand HTML Symbol Entity not rendered on Monthly insights

### ISSUE THREAD

**Issue by deuterium** [bminusl/ihatetobudget#8]
Symbol & is displayed as &amp; on Monthly insights page.
Other symbols on number row work correctly.

![image](https://user-images.githubusercontent.com/571738/119420165-aa28d200-bcb0-11eb-83b7-c3e0bd5dfd72.png)

Symbol rendered properly on Categories, sheets, new expensive pages.

**Comment by bminusl** [comment]
This was an simple fix.

I also released `v1.5.5`.
